//%attributes = {"invisible":true}
C_LONGINT:C283(<>Lon_MemoLastEvent)
C_LONGINT:C283(<>Lon_strokeWidth)
C_REAL:C285(<>svgArea_Lon_Beta)
C_REAL:C285(<>svgArea_Lon_hotFix)
C_REAL:C285(<>svgArea_Num_Version)
C_TEXT:C284(<>Txt_callbackMethod)
C_TEXT:C284(<>Txt_DefaultOnErrorMethod)
C_TEXT:C284(<>Txt_fillColor)
C_TEXT:C284(<>Txt_MemoLastID)
C_TEXT:C284(<>Txt_strokeColor)